language: node_js

sudo: false
dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true
    - GK_LOCK_YARN_OPTS='--ignore-engines'
    - secure: "w8KUA_Rqkh28LT1H2Q9NRA"


cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "test"
      if: |
        branch ~= /^develop$|^master$|^release\/.+$/ OR \
        type = pull_request OR \
        env(RESTRICT_PUSH_BUILDS) != true
      addons:
        chrome: stable
        coverity_scan:
          project:
            name: "baylee-d/ember-osf-web"
          notification_email: baylee@cos.io
          branch_pattern: coverity_scan
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add greenkeeper-lockfile@1
        - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
        - greenkeeper-lockfile-update
      script:
        - yarn lint && yarn test:node-tests && yarn test:cover
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    - stage: "deploy handbook"
      if: |
        branch = develop AND \
        type != pull_request AND \
        env(DEPLOY_KEY) IS present
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
      env:
        - HANDBOOK_ENABLED=1
        - MIRAGE_ENABLED=1
        - SHOW_DEV_BANNER=1
        - A11Y_AUDIT=0
        - NODE_OPTIONS=--max-old-space-size=4096
        - TARGET_BRANCH=gh-pages
      script:
        - export ROOT_URL="/${TRAVIS_REPO_SLUG##*\/}/"
        - export ASSETS_PREFIX="${ROOT_URL}"
        - ember build --environment=production
        - cp dist/index.html dist/404.html
      deploy:
        provider: script
        skip-cleanup: true
        script: scripts/handbook_deploy.sh
        on:
          branch: develop
